export const catalogProductsData = [
  {
    id: 1,
    name: 'Arabica Single Origin',
    price: '50.000',
    weight: 'Berat : 250g',
    img: 'assets/img/arabica.png',
    desc: 'Kopi single origin dengan karakter floral khas pegunungan Sukabumi.',
  },
  {
    id: 2,
    name: 'Robusta Blend',
    price: '45.000',
    weight: 'Berat : 250g',
    img: 'assets/img/robusta.png',
    desc: 'Perpaduan Robusta terbaik dengan sedikit aftertaste cokelat, kuat dan seimbang.',
  },
  {
    id: 3,
    name: 'Liberica Premium',
    price: '60.000',
    weight: 'Berat : 250g',
    img: 'assets/img/premium.png',
    desc: 'Liberica eksklusif Sukabumi, aroma smoky dan rasa tebal yang langka.',
  },
  {
    id: 4,
    name: 'Excelsa Spesial',
    price: '58.000',
    weight: 'Berat : 250g',
    img: 'assets/img/premium-1.png',
    desc: 'Excelsa dari perkebunan lokal dengan rasa fruity dan sedikit asam menyegarkan.',
  },
  {
    id: 5,
    name: 'Arabica Beans',
    price: '52.000',
    weight: 'Berat : 250g',
    img: 'assets/img/home-page.jpg',
    desc: 'Biji Arabica pilihan dari dataran tinggi Sukabumi dengan aroma lembut dan cita rasa manis alami.',
  },
  {
    id: 6,
    name: 'Robusta Ground Coffee',
    price: '45.000',
    weight: 'Berat : 250g',
    img: 'assets/img/robusta-powder.jpg',
    desc: 'Kopi Robusta bubuk khas Sukabumi dengan rasa kuat dan pekat untuk energi pagi.',
  },
  {
    id: 7,
    name: 'Drip Bags',
    price: '40.000',
    weight: 'Berat : 200g',
    img: 'assets/img/drip-bag.jpg',
    desc: 'Kemasan praktis kopi Arabica Sukabumi, tinggal seduh, nikmati rasa otentiknya.',
  },
  {
    id: 8,
    name: 'Liberica Powder',
    price: '55.000',
    weight: 'Berat : 250g',
    img: 'assets/img/liberica-powder.jpg',
    desc: 'Bubuk kopi Liberica dengan aroma intens dan kepekatan rasa yang dalam.',
  },
  {
    id: 9,
    name: 'Arabica Blend',
    price: '48.000',
    weight: 'Berat : 250g',
    img: 'assets/img/arabica.png',
    desc: 'Campuran Arabica lokal yang seimbang antara manis, asam, dan lembut.',
  },
  {
    id: 10,
    name: 'Robusta Black',
    price: '43.000',
    weight: 'Berat : 250g',
    img: 'assets/img/robusta.png',
    desc: 'Kopi hitam pekat khas Sukabumi dengan rasa kuat dan aroma tanah yang khas.',
  },
];
